deploymentName: gatewayserver-deployment
deploymentLabel: gatewayserver

replicaCount: 1

image:
  repository: naveejr/microbank-gatewayserver
  tag: latest

containerPort: 8072

service:
  type: LoadBalancer
  port: 8072
  targetPort: 8072

profile_enabled: true
zipkin_enabled: true
config_enabled: true
eureka_enabled: true