deploymentName: eurekaserver-deployment
deploymentLabel: eurekaserver

replicaCount: 1

image:
  repository: naveejr/microbank-eurekaserver
  tag: latest

containerPort: 8070

service:
  type: ClusterIP
  port: 8070
  targetPort: 8070

profile_enabled: true
zipkin_enabled: true
config_enabled: true
eureka_enabled: false