deploymentName: accounts-deployment
deploymentLabel: accounts

replicaCount: 1

image:
  repository: naveejr/microbank-accounts
  tag: latest

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

profile_enabled: true
zipkin_enabled: true
config_enabled: true
eureka_enabled: true