deploymentName: configserver-deployment
deploymentLabel: configserver

replicaCount: 1

image:
  repository: naveejr/microbank-configserver
  tag: latest

containerPort: 8071

service:
  type: LoadBalancer
  port: 8071
  targetPort: 8071

profile_enabled: true
zipkin_enabled: true
config_enabled: false
eureka_enabled: false