apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
  labels:
    app: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      name: eurekaserver
      labels:
        app: eurekaserver
    spec:
      containers:
        - name: eurekaserver
          image: naveejr/microbank-eurekaserver:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: microbank-configmap
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_ZIPKIN_BASEURL
                  name: microbank-configmap
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CONFIG_IMPORT
                  name: microbank-configmap
      restartPolicy: Always
