apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      name: accounts
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: naveejr/microbank-accounts:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: microbank-configmap
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_ZIPKIN_BASEURL
                  name: microbank-configmap
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CONFIG_IMPORT
                  name: microbank-configmap
      restartPolicy: Always
