apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-deployment
  labels:
    app: cards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards
  template:
    metadata:
      name: cards
      labels:
        app: cards
    spec:
      containers:
        - name: cards
          image: naveejr/microbank-cards:latest
          ports:
            - containerPort: 9000
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: microbank-configmap
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_ZIPKIN_BASEURL
                  name: microbank-configmap
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CONFIG_IMPORT
                  name: microbank-configmap
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                  name: microbank-configmap
      restartPolicy: Always
