version: "3.8"

services:

  configserver:
    image: naveejr/microbank-configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - mirobank
  eurekaserver:
    image: naveejr/microbank-eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - mirobank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
  accounts:
    image: naveejr/microbank-accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - mirobank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
  
  loans:
    image: naveejr/microbank-loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - mirobank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    
  cards:
    image: naveejr/microbank-cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - mirobank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
  gatewayserver:
    image: naveejr/microbank-gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
     - mirobank
    depends_on:
      - configserver
      - eurekaserver
      - accounts
      - cards
      - loans
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
networks:
  mirobank:
